#!/bin/bash

: '
	Author Lander Usategui lander.usategui@gmail.com
'
function rtDeploy()
{
  cp kernel8.img /boot
  cp *.dtb /boot
  cp -r overlays /boot
  cp -r 64_modules/lib/firmware /lib
  cp -r 64_modules/lib/modules/4.9.47-rt37-v7+ /lib/modules
  echo "kernel=kernel8.img" >> /boot/config.txt
  sed -i "1 s|$| dwc_otg.fiq_enable=0 dwc_otg.fiq_fsm_enable=0|" /boot/cmdline.txt
  echo "Done"
}

function main()
{
  CURRENT_USER=`whoami`

  if [ "${CURRENT_USER}" = "root" ]; then
      rtDeploy
  else
    echo "\"sudo\" is required..."
  fi
}

# Start script
main
